[package]
name = "sim"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
argh = "0.1.13"
env_logger = "0.11.8"
libc = "0.2.176"
simmerv = { version = "0.3.0", path = ".." }
termios = "0.3.3"
zstd = "0.13.3"
